// use try catch blocks in case of async and await. .then .catch in case of promises. thats it
// try{
// }catch(ex){
//     res.status(500).send("internal server error....") // 
// }